export const stimulus = {
	0: "Please take a deep breath",
	1: "Please take a force breath",
	2: "Please cough once",
	3: "Take a deep breath in and say 'Aaa' as in 'Basket'  while breathing out",
	4: "Take a deep breath in and say 'Ooo' as in 'Horrible'  while breathing out",
	5: "Take a deep breath in and say 'Eee' as in 'peace'  while breathing out",
	6: "Take a deep breath in and say 'Sss' as in 'Shakira'  while breathing out",
	7: "Take a deep breath in and say 'Uuu' as in 'You'  while breathing out",
	8: "Take a deep breath in and say 'Zzz' as in 'Fuzz' while breathing out",
	9: "Take a deep breath in and say 'Yee' as in 'Yeah'  while breathing out",
	10: "Please take a deep breath - With food in your mouth (don't chew while recording)",
	11: "Please take a force breath - With food in your mouth (don't chew while recording)",
	12: "Please cough once - With food in your mouth (don't chew while recording)",
	13: "Take a deep breath in and say 'Aaa' as in 'Basket'  while breathing out - With food in your mouth (don't chew while recording)",
	14: "Take a deep breath in and say 'Ooo' as in 'Horrible'  while breathing out - With food in your mouth (don't chew while recording)",
	15: "Take a deep breath in and say 'Eee' as in 'peace'  while breathing out - With food in your mouth (don't chew while recording)",
	16: "Take a deep breath in and say 'Sss' as in 'Shakira'  while breathing out - With food in your mouth (don't chew while recording)",
	17: "Take a deep breath in and say 'Uuu' as in 'You'  while breathing out - With food in your mouth (don't chew while recording)",
	18: "Take a deep breath in and say 'Zzz' as in 'Fuzz' while breathing out - With food in your mouth (don't chew while recording)",
	19: "Take a deep breath in and say 'Yee' as in 'Yeah'  while breathing out - With food in your mouth (don't chew while recording)",
};
